# Site settings
title: F4 Developer
description: "Stanisław Kowański - programowanie. Web development, WordPress development, pluginy Minecraft, setup i administracja stron internetowych. Full stack developer. Zapraszam do kontaktu!"
baseurl: ""
url: "https://www.f4dev.me"

# User settings
username: Stanislaw Kowanski
user_title: Stanisław Kowański - F4 Developer
email: root@f4dev.me
github_username:  kovansky
profile_picture: https://www.f4dev.me/logo.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: Start
      url: /
      key_trigger: 1
    - title: O mnie
      url: /about
      key_trigger: 2
    - title: Portfolio
      url: /portfolio
      key_trigger: 3
    - title: Oferta
      url: /offer
      key_trigger: 4
  section_2:
    - title: GitHub
      url: http://www.github.com/kovansky
      key_trigger: g
    - title: Szukaj
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: PluginController
    url: /plugincontroller
    image: /assets/img/portfolio/PluginController.png
    tags:
      - Java
  - name: MCTraps
    url: /mctraps
    image: /assets/img/portfolio/MCTraps.png
    tags:
      - Web
      - Java
  - name: RobRoyArt
    url: /robroyart
    image: /assets/img/portfolio/robroyart.png
    tags:
      - Web
  - name: Autorskie Studio Projektu Qubatura
    url: /asp-qubatura
    image: /assets/img/portfolio/Qubatura.png
    tags:
      - Web

langs:
  - Java
  - Web

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
